function [N,T1,Y1,C1,T2,Y2,C2,T3,Y3,C3] = Import(n)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\nfigu\Documents\MATLAB\FitGaussians\7.15_001.lvm
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/07/15 19:30:24

%% Initialize variables.

if n < 10
    STR = strcat('00',num2str(n));
elseif n< 100
    STR = strcat('0',num2str(n));
else 
    STR = num2str(n);
end

filename = strcat('C:\Users\nfigu\Documents\MATLAB\FitGaussians\7.15_',STR,'.lvm');
delimiter = '\t';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
N = dataArray{:, 1};
T1 = dataArray{:, 2};
Y1 = dataArray{:, 3};
C1 = dataArray{:, 4};
T2 = dataArray{:, 5};
Y2 = dataArray{:, 6};
C2 = dataArray{:, 7};
T3 = dataArray{:, 8};
Y3 = dataArray{:, 9};
C3 = dataArray{:, 10};
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

end